# Generated by Django 5.2.6 on 2026-07-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('framework', 'Frameworks'), ('aiml', 'AI / ML'), ('database', 'Databases'), ('tool', 'Tools')], default='tool', max_length=20),
        ),
    ]
