# Generated by Django 5.2.6 on 2026-07-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='Comma-separated list of key features'),
        ),
        migrations.AddField(
            model_name='project',
            name='my_contribution',
            field=models.TextField(blank=True, help_text='Your contribution to this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_solved',
            field=models.TextField(blank=True, help_text='Problem solved by this project'),
        ),
    ]
