# Generated by Django 5.2.6 on 2026-07-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_key_features_project_my_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency_label',
            field=models.CharField(choices=[('core', 'Core'), ('comfortable', 'Comfortable'), ('exploring', 'Exploring')], default='comfortable', max_length=20),
        ),
    ]
