# Generated by Django 6.0.7 on 2026-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_proficiency_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency_label',
            field=models.CharField(choices=[('core', 'Core'), ('comfortable', 'Comfortable'), ('exploring', 'Learning')], default='comfortable', max_length=20),
        ),
    ]
