# Generated by Django 6.0.7 on 2026-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_skill_proficiency_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency_label',
            field=models.CharField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default='comfortable', max_length=20),
        ),
    ]
